const GAMES_LIST_REQUEST="GAMES_LIST_REQUEST";
const GAMES_LIST_SUCCESS="GAMES_LIST_SUCCESS";
const GAMES_LIST_FAILURE="GAMES_LIST_FAILURE";
const CREATE_GAME_REQUEST="CREATE_GAME_REQUEST";
const CREATE_GAME_SUCCESS="CREATE_GAME_SUCCESS";
const CREATE_GAME_FAILURE="CREATE_GAME_FAILURE";
const GAME_DELETE_FAILURE="GAME_DELETE_FAILURE";
const GAME_DELETE_SUCCESS="GAME_DELETE_SUCCESS";
const GAME_DELETE_REQUEST="GAME_DELETE_REQUEST";
const ADD_PLAYER_REQUEST="ADD-PLAYER_REQUEST";
const ADD_PLAYER_SUCCESS="ADD-PLAYER_SUCCESS";
const ADD_PLAYER_FAILURE="ADD-PLAYER_FAILURE";
const types = {
	GAMES_LIST_REQUEST,
 	GAMES_LIST_SUCCESS,
 	GAMES_LIST_FAILURE,
 	CREATE_GAME_REQUEST,
 	CREATE_GAME_SUCCESS,
 	CREATE_GAME_FAILURE,
 	GAME_DELETE_FAILURE,
 	GAME_DELETE_SUCCESS,
 	GAME_DELETE_REQUEST,
	ADD_PLAYER_REQUEST,
	ADD_PLAYER_SUCCESS,
	ADD_PLAYER_FAILURE,
}

export default types
