const COMMENTS_LIST_REQUEST="COMMENTS_LIST_REQUEST";
const COMMENTS_LIST_SUCCESS="COMMENTS_LIST_SUCCESS";
const COMMENTS_LIST_FAILURE="COMMENTS_LIST_FAILURE";
const CREATE_COMMENT_REQUEST="CREATE_COMMENT_REQUEST";
const CREATE_COMMENT_SUCCESS="CREATE_COMMENT_SUCCESS";
const CREATE_COMMENT_FAILURE="CREATE_COMMENT_FAILURE";
const COMMENT_DELETE_FAILURE="COMMENT_DELETE_FAILURE";
const COMMENT_DELETE_SUCCESS="COMMENT_DELETE_SUCCESS";
const COMMENT_DELETE_REQUEST="COMMENT_DELETE_REQUEST";

const types = {
	COMMENTS_LIST_REQUEST,
 	COMMENTS_LIST_SUCCESS,
 	COMMENTS_LIST_FAILURE,
 	CREATE_COMMENT_REQUEST,
 	CREATE_COMMENT_SUCCESS,
 	CREATE_COMMENT_FAILURE,
 	COMMENT_DELETE_FAILURE,
 	COMMENT_DELETE_SUCCESS,
 	COMMENT_DELETE_REQUEST,
	
}

export default types
