const USER_LIST_REQUEST="USER_LIST_REQUEST";
const USER_LIST_SUCCESS="USER_LIST_SUCCESS";
const USER_LIST_FAILURE="USER_LIST_FAILURE";
const CREATE_USER_REQUEST="CREATE_USER_REQUEST";
const CREATE_USER_SUCCESS="CREATE_USER_SUCCESS";
const CREATE_USER_FAILURE="CREATE_USER_FAILURE";
const LOGIN_USER_REQUEST="LOGIN_USER_REQUEST";
const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS";
const LOGIN_USER_FAILURE="LOGIN_USER_FAILURE";
const USER_DELETE_FAILURE="USER_DELETE_FAILURE";
const USER_DELETE_SUCCESS="USER_DELETE_SUCCESS";
const USER_DELETE_REQUEST="USER_DELETE_REQUEST";


const types = {
	USER_LIST_REQUEST,
 	USER_LIST_SUCCESS,
 	USER_LIST_FAILURE,
 	CREATE_USER_REQUEST,
 	CREATE_USER_SUCCESS,
 	CREATE_USER_FAILURE,
	LOGIN_USER_REQUEST,
 	LOGIN_USER_SUCCESS,
 	LOGIN_USER_FAILURE,
 	USER_DELETE_FAILURE,
 	USER_DELETE_SUCCESS,
 	USER_DELETE_REQUEST,
	
}

export default types
